import { MYBatCollectorEnum } from './';
import { MYLolifeSiteClassificationEnum } from './';
import { MYPointCountHabitatEnum } from './';
import { MYSykeButterFlyCensusWindEnum } from './';
import { MYWaterbirdCensusPeriodEnum } from './';
import { MYWaterbirdHabitatEnum } from './';
import { WBCSpeciesAbundanceEnum } from './';
import { WBCCloudAndRainEnum } from './';
import { WBCIceCoverEnum } from './';
import { WBCBerriesAndConesEnum } from './';
import { WBCSnowAndIceOnTreesEnum } from './';
import { WBCSnowCoverEnum } from './';
import { WBCTypeOfSnowCoverEnum } from './';
import { WBCVisibilityEnum } from './';
import { WBCWaterbodiesEnum } from './';
import { WBCWayOfTravelEnum } from './';
import { WBCWindEnum } from './';

/* tslint:disable */
/*
* This file was automatically generated.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the command to regenerate this file.
*/
export class GatheringFact {
  "@context"?: string;
  id?: string;
  "@type"?: string;
  batCollector?: MYBatCollectorEnum;
  binocularsUsed?: boolean;
  censusAreaHectares?: number;
  documentation?: string;
  invasiveControlOtherExpensesInEuros?: number;
  invasiveControlWorkHours?: number;
  lineTransectSegmentCounted?: boolean;
  lineTransectSegmentMetersEnd?: number;
  lineTransectSegmentMetersStart?: number;
  lolifeSiteClassification?: MYLolifeSiteClassificationEnum;
  lolifeSiteClassificationComments?: string;
  marineArea?: string;
  marineMammalExpertise?: string;
  observationTools?: string;
  observedAreaHectares?: number;
  pointCountHabitat?: MYPointCountHabitatEnum;
  shorelineLengthMeters?: number;
  spottingScopeUsed?: boolean;
  sunniness?: number;
  sykeButterFlyCensusWind?: MYSykeButterFlyCensusWindEnum;
  sykeButterFlyCensusWindEnd?: MYSykeButterFlyCensusWindEnum;
  sykeButterFlyCensusWindStart?: MYSykeButterFlyCensusWindEnum;
  waterbirdCensusPeriod?: MYWaterbirdCensusPeriodEnum;
  waterbirdHabitat?: MYWaterbirdHabitatEnum;
  ykjSquareNumber?: string;
  ACAFLAonAlder?: number;
  ACAFLAonBirch?: number;
  ACAFLAonGround?: number;
  ACAFLAonPine?: number;
  ACAFLAonSpruce?: number;
  CARSPIonAlder?: number;
  CARSPIonBirch?: number;
  CARSPIonGround?: number;
  CARSPIonPine?: number;
  CARSPIonSpruce?: number;
  LOXIAonAlder?: number;
  LOXIAonBirch?: number;
  LOXIAonGround?: number;
  LOXIAonPine?: number;
  LOXIAonSpruce?: number;
  abundanceBOMGAR?: WBCSpeciesAbundanceEnum;
  abundancePINENU?: WBCSpeciesAbundanceEnum;
  abundanceTURPIL?: WBCSpeciesAbundanceEnum;
  birdFeederCount?: number;
  birdFeederCountBiotopeA?: number;
  birdFeederCountBiotopeB?: number;
  birdFeederCountBiotopeC?: number;
  birdFeederCountBiotopeD?: number;
  birdFeederCountBiotopeE?: number;
  birdFeederCountBiotopeF?: number;
  birdFeederCountBiotopeG?: number;
  birdFeederCountBiotopeH?: number;
  cloudAndRain?: WBCCloudAndRainEnum;
  descriptionBiotopeF?: string;
  feedingStationCount?: number;
  feedingStationCountBiotopeA?: number;
  feedingStationCountBiotopeB?: number;
  feedingStationCountBiotopeC?: number;
  feedingStationCountBiotopeD?: number;
  feedingStationCountBiotopeE?: number;
  feedingStationCountBiotopeF?: number;
  feedingStationCountBiotopeG?: number;
  feedingStationCountBiotopeH?: number;
  iceCover?: WBCIceCoverEnum;
  meanTemperature?: number;
  observerCount?: number;
  observerID?: number;
  pineConesAtCensus?: WBCBerriesAndConesEnum;
  routeID?: number;
  routeLength?: number;
  routeLengthBiotopeA?: number;
  routeLengthBiotopeB?: number;
  routeLengthBiotopeC?: number;
  routeLengthBiotopeD?: number;
  routeLengthBiotopeE?: number;
  routeLengthBiotopeF?: number;
  routeLengthBiotopeG?: number;
  routeLengthBiotopeH?: number;
  routeLengthChange?: number;
  routeLengthChangeBiotopeA?: number;
  routeLengthChangeBiotopeB?: number;
  routeLengthChangeBiotopeC?: number;
  routeLengthChangeBiotopeD?: number;
  routeLengthChangeBiotopeE?: number;
  routeLengthChangeBiotopeF?: number;
  routeLengthChangeBiotopeG?: number;
  routeLengthChangeBiotopeH?: number;
  snowAndIceOnTrees?: WBCSnowAndIceOnTreesEnum;
  snowCover?: WBCSnowCoverEnum;
  sorbusBerriesAtCensus?: WBCBerriesAndConesEnum;
  sorbusBerriesEarlyFall?: WBCBerriesAndConesEnum;
  spruceConesAtCensus?: WBCBerriesAndConesEnum;
  typeOfSnowCover?: WBCTypeOfSnowCoverEnum;
  visibility?: WBCVisibilityEnum;
  waterbodies?: WBCWaterbodiesEnum;
  wayOfTravel?: WBCWayOfTravelEnum;
  wayOfTravelNotes?: string;
  wind?: WBCWindEnum;
}
