version: '3'

services:
  redis:
    env_file:
      - .env
    extends:
      file: tools/docker/docker-compose.shared.yml
      service: redis
    command: sh -c 'redis-server --requirepass $${REDIS_PASSWORD}'

  rabbit:
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    extends:
      file: tools/docker/docker-compose.shared.yml
      service: rabbit

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgre_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 3

  elastic:
    ports:
      - 9200:9200
    extends:
      file: tools/docker/docker-compose.shared.yml
      service: elastic-single

  store:
    depends_on:
      database:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      elastic:
        condition: service_healthy
    env_file:
      - .env
    build:
      context: ./
      dockerfile: tools/docker/store/Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - .env:/app/.env
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:3000/status || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 7

  kibana:
    image: kibana:7.11.2
    depends_on:
      - elastic
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elastic:9200

  store-worker:
    depends_on:
      store:
        condition: service_healthy
    env_file:
      - .env
    build:
      context: ./
      dockerfile: tools/docker/store/Dockerfile
      target: dev
    volumes:
      - .:/app
    environment:
      IS_WORKER: 'true'
      DW_SOURCES: 'KE.3,KE.007,KE.006'
      ID_RESOLVER: 'http://tun.fi/'
    command: 'nx serve store-worker'

volumes:
  elastic_data:
    driver: local
  postgre_data:
    driver: local
  store_node_modules:
    driver: local
  redis:
    driver: local

